spring:
  application:
    name: user-info-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8585
      name: user-info-service
server:
  port: 8084
