spring:
  application:
    name: user-info-service
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888
server:
  port: 8084

baseUrl: http://gateway-service/
