spring:
  application:
    name: user-info-service
  profiles:
    active: native
  config:
#    import: optional:configserver:http://localhost:8888
    import: optional:configserver:http://8.222.225.41:8888
server:
  port: 8084

baseUrl: http://gateway-service/

management:
  tracing:
    sampling:
      probability: 1.0