spring:
  application:
    name: user-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8585
      name: user-service
server:
  port: 8081
logging:
  level:
    org.springframework.web.servlet.handler.SimpleUrlHandlerMapping: OFF