spring:
  application:
    name: keycloak-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8585
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
server:
  port: 8081

#management:
#  tracing:
#    sampling:
#      probability: 1.0

#openapi:
#  service:
#    title: keycloak-service
#    version: 1.0.0
#    url: http://localhost:9000
#
#springdoc:
#  api-docs:
#    path: /keycloak-service/v3/api-docs
#  swagger-ui:
#    path: /keycloak-service/swagger-ui.html