spring:
  application:
    name: user-service
  profiles:
    active: native
  config:
#    import: optional:configserver:http://localhost:8888
    import: optional:configserver:http://8.222.225.41:8888
server:
  port: 8081
logging:
  level:
    org.springframework.web.servlet.handler.SimpleUrlHandlerMapping: OFF

management:
  tracing:
    sampling:
      probability: 1.0