spring:
  application:
    name: user-service
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888
server:
  port: 8081
logging:
  level:
    org.springframework.web.servlet.handler.SimpleUrlHandlerMapping: OFF