spring:
  application:
    name: category-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8585
      name: category-service
  main:
    allow-bean-definition-overriding: true
server:
  port: 8087

