spring:
  application:
    name: category-service
  profiles:
    active: dev
  config:
    import: optional:configserver:http://8.222.225.41:8888
  main:
    allow-bean-definition-overriding: true
server:
  port: 8087

