spring:
  application:
    name: product-service
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888
#    import: optional:configserver:http://8.222.225.41:8888
server:
  port: 8089

baseUrl: http://gateway-service/

