spring:
  application:
    name: product-for-sale-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8585
      name: product-for-sale-service
server:
  port: 8090

