
spring:
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8585
      name: chat-service
  application:
    name: chat-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  main:
    allow-bean-definition-overriding: true
server:
  port: 8082

