
spring:
  application:
    name: chat-service
  rabbitmq:
    host: localhost
    port: 5672
    username: rithysak
    password: rithysak
    virtual-host: /
  main:
    allow-bean-definition-overriding: true

server:
  port: 8082

