spring:
  application:
    name: chat-service
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  main:
    allow-bean-definition-overriding: true
server:
  port: 8082
baseUrl: http://gateway-service/
