spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/goselling/go-selling-config.git
          clone-on-start: true
          default-label: master
server:
  port: 8585