spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/renrithysak095/configuration_file.git
          clone-on-start: true
          default-label: main
server:
  port: 8585
