spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: git@github.com:goselling/go-selling-config.git
          clone-on-start: true
          default-label: main
server:
  port: 8585